Repository PSR-Co/SERVER, pull requests merged in 2023-07, with the labels that each got.

#4 [chore] github actions test
  src/test/kotlin/com/psr/psr/PsrApplicationTests.kt
Labels: 🐣 chae-eun

#6 #5 jasypt 적용
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .gitignore
  build.gradle.kts
  src/main/kotlin/com/psr/psr/global/config/JasyptConfig.kt
  src/main/resources/application.properties
  src/main/resources/application.yaml
Labels: ☀️ seoyeon

#8 [feat] Spring security 기본 설정
  build.gradle.kts
  src/main/kotlin/com/psr/psr/global/Constant.kt
  src/main/kotlin/com/psr/psr/global/config/JwtSecurityConfig.kt
  src/main/kotlin/com/psr/psr/global/config/WebSecurityConfig.kt
  src/main/kotlin/com/psr/psr/global/jwt/JwtFilter.kt
  src/main/kotlin/com/psr/psr/global/jwt/UserDetailsImpl.kt
  src/main/kotlin/com/psr/psr/global/jwt/UserDetailsServiceImpl.kt
  src/main/kotlin/com/psr/psr/global/jwt/dto/TokenRes.kt
  src/main/kotlin/com/psr/psr/global/jwt/utils/JwtUtils.kt
  src/main/kotlin/com/psr/psr/user/entity/User.kt
  src/main/resources/application.yaml
Labels: 🐣 chae-eun, 🪜 infra

#10 [feat] DB 생성
  src/main/kotlin/com/psr/psr/chat/entity/ChatRoom.kt
  src/main/kotlin/com/psr/psr/cs/entity/Faq.kt
  src/main/kotlin/com/psr/psr/cs/entity/FaqType.kt
  src/main/kotlin/com/psr/psr/cs/entity/Notice.kt
  src/main/kotlin/com/psr/psr/inquiry/entity/Inquiry.kt
  src/main/kotlin/com/psr/psr/inquiry/entity/InquiryStatus.kt
  src/main/kotlin/com/psr/psr/notification/entity/Notification.kt
  src/main/kotlin/com/psr/psr/order/entity/Order.kt
  src/main/kotlin/com/psr/psr/order/entity/OrderStatus.kt
  src/main/kotlin/com/psr/psr/product/entity/ReportCategory.kt
  src/main/kotlin/com/psr/psr/product/entity/product/Product.kt
  src/main/kotlin/com/psr/psr/product/entity/product/ProductImg.kt
  src/main/kotlin/com/psr/psr/product/entity/product/ProductLike.kt
  src/main/kotlin/com/psr/psr/product/entity/product/ProductReport.kt
  src/main/kotlin/com/psr/psr/product/entity/review/Review.kt
  src/main/kotlin/com/psr/psr/product/entity/review/ReviewReport.kt
  src/main/kotlin/com/psr/psr/user/entity/BusinessInfo.kt
  src/main/kotlin/com/psr/psr/user/entity/Category.kt
  src/main/kotlin/com/psr/psr/user/entity/Provider.kt
  src/main/kotlin/com/psr/psr/user/entity/Type.kt
  src/main/kotlin/com/psr/psr/user/entity/User.kt
  src/main/kotlin/com/psr/psr/user/entity/UserInterest.kt
Labels: 🔮 feat, 😽 sojung

#11 [feat] 스프링 시큐리티 예외처리 및 role 적용
  src/main/kotlin/com/psr/psr/global/Constant.kt
  src/main/kotlin/com/psr/psr/global/config/WebSecurityConfig.kt
  src/main/kotlin/com/psr/psr/global/exception/BaseResponseCode.kt
  src/main/kotlin/com/psr/psr/global/jwt/JwtFilter.kt
  src/main/kotlin/com/psr/psr/global/jwt/UserDetailsImpl.kt
  src/main/kotlin/com/psr/psr/global/jwt/exception/JwtAccessDeniedHandler.kt
  src/main/kotlin/com/psr/psr/global/jwt/exception/JwtAuthenticationEntryPoint.kt
  src/main/kotlin/com/psr/psr/global/jwt/utils/JwtUtils.kt
Labels: 🔮 feat, 🐣 chae-eun, 🪜 infra

#14 [feat] 회원가입 API 생성
  src/main/kotlin/com/psr/psr/global/Constant.kt
  src/main/kotlin/com/psr/psr/global/config/WebSecurityConfig.kt
  src/main/kotlin/com/psr/psr/global/dto/BaseResponse.kt
  src/main/kotlin/com/psr/psr/global/exception/BaseRes.kt
  src/main/kotlin/com/psr/psr/global/exception/BaseResponseCode.kt
  src/main/kotlin/com/psr/psr/global/exception/ExceptionHandler.kt
  src/main/kotlin/com/psr/psr/global/jwt/JwtFilter.kt
  src/main/kotlin/com/psr/psr/global/jwt/UserDetailsImpl.kt
  src/main/kotlin/com/psr/psr/global/jwt/UserDetailsServiceImpl.kt
  src/main/kotlin/com/psr/psr/global/jwt/dto/TokenRes.kt
  src/main/kotlin/com/psr/psr/global/jwt/utils/JwtUtils.kt
  src/main/kotlin/com/psr/psr/user/controller/UserController.kt
  src/main/kotlin/com/psr/psr/user/dto/SignUpReq.kt
  src/main/kotlin/com/psr/psr/user/dto/UserInterestReq.kt
  src/main/kotlin/com/psr/psr/user/entity/Category.kt
  src/main/kotlin/com/psr/psr/user/entity/Type.kt
  src/main/kotlin/com/psr/psr/user/entity/User.kt
  src/main/kotlin/com/psr/psr/user/entity/UserInterest.kt
  src/main/kotlin/com/psr/psr/user/repository/UserRepository.kt
  src/main/kotlin/com/psr/psr/user/service/UserService.kt
Labels: 🔮 feat, 🐣 chae-eun, 🕸️ fix

#17 [fix] 회원가입 API Valid Annotation 적용
  build.gradle.kts
  src/main/kotlin/com/psr/psr/global/Constant.kt
  src/main/kotlin/com/psr/psr/global/exception/BaseResponseCode.kt
  src/main/kotlin/com/psr/psr/global/exception/ExceptionHandler.kt
  src/main/kotlin/com/psr/psr/user/controller/UserController.kt
  src/main/kotlin/com/psr/psr/user/dto/SignUpReq.kt
  src/main/kotlin/com/psr/psr/user/service/UserService.kt
Labels: 🔮 feat, 🐣 chae-eun, 🎀 chore, 🕸️ fix

#18 [feat] 문의하기 등록 API 생성
  src/main/kotlin/com/psr/psr/global/config/WebSecurityConfig.kt
  src/main/kotlin/com/psr/psr/global/exception/BaseResponseCode.kt
  src/main/kotlin/com/psr/psr/inquiry/controller/InquiryController.kt
  src/main/kotlin/com/psr/psr/inquiry/dto/InquiryReq.kt
  src/main/kotlin/com/psr/psr/inquiry/entity/Inquiry.kt
  src/main/kotlin/com/psr/psr/inquiry/service/InquiryService.kt
  src/main/kotlin/com/psr/psr/order/entity/Order.kt
Labels: 🔮 feat, ☀️ seoyeon

#20 [feat] 로그인 API & Token User 객체 반환
  src/main/kotlin/com/psr/psr/global/exception/BaseResponseCode.kt
  src/main/kotlin/com/psr/psr/global/jwt/UserAccount.kt
  src/main/kotlin/com/psr/psr/global/jwt/UserDetailsServiceImpl.kt
  src/main/kotlin/com/psr/psr/user/controller/UserController.kt
  src/main/kotlin/com/psr/psr/user/dto/LoginReq.kt
  src/main/kotlin/com/psr/psr/user/repository/UserRepository.kt
  src/main/kotlin/com/psr/psr/user/service/UserService.kt
Labels: 🔮 feat, 🐣 chae-eun, 👩🏻‍💻 users

#22 [feat] 닉네임 중복 체크 및 Redis 설정
  build.gradle.kts
  src/main/kotlin/com/psr/psr/global/Constant.kt
  src/main/kotlin/com/psr/psr/global/config/RedisConfig.kt
  src/main/kotlin/com/psr/psr/global/config/WebSecurityConfig.kt
  src/main/kotlin/com/psr/psr/global/jwt/utils/JwtUtils.kt
  src/main/kotlin/com/psr/psr/user/controller/UserController.kt
  src/main/kotlin/com/psr/psr/user/dto/CheckNicknameReq.kt
  src/main/kotlin/com/psr/psr/user/service/UserService.kt
  src/main/resources/application.yaml
Labels: 🔮 feat, 🐣 chae-eun, 🪜 infra, 👩🏻‍💻 users
