Repository PSR-Co/SERVER, pull requests merged in 2023-11, with the labels that each got.

#191 [docs] 담당 스웨거 설명 설정
  src/main/kotlin/com/psr/psr/cs/controller/CsController.kt
  src/main/kotlin/com/psr/psr/cs/dto/response/NoticeListRes.kt
  src/main/kotlin/com/psr/psr/cs/dto/response/NoticeRes.kt
  src/main/kotlin/com/psr/psr/product/controller/ProductController.kt
  src/main/kotlin/com/psr/psr/product/dto/request/CreateproductReq.kt
  src/main/kotlin/com/psr/psr/product/dto/request/ReportProductReq.kt
  src/main/kotlin/com/psr/psr/product/dto/response/GetHomePageRes.kt
  src/main/kotlin/com/psr/psr/product/dto/response/GetLikeProductsRes.kt
  src/main/kotlin/com/psr/psr/product/dto/response/GetMyProductsRes.kt
  src/main/kotlin/com/psr/psr/product/dto/response/GetProductDetailRes.kt
  src/main/kotlin/com/psr/psr/product/dto/response/GetProductsByUserRes.kt
  src/main/kotlin/com/psr/psr/product/dto/response/GetProductsRes.kt
  src/main/kotlin/com/psr/psr/product/dto/response/GetSearchProducts.kt
  src/main/kotlin/com/psr/psr/product/dto/response/MainProduct.kt
  src/main/kotlin/com/psr/psr/product/dto/response/MainTopProduct.kt
  src/main/kotlin/com/psr/psr/product/dto/response/MyProduct.kt
  src/main/kotlin/com/psr/psr/product/dto/response/PopularProductDetail.kt
  src/main/kotlin/com/psr/psr/product/dto/response/ProductDetail.kt
  src/main/kotlin/com/psr/psr/review/controller/ReviewController.kt
  src/main/kotlin/com/psr/psr/review/dto/GetProductDetailRes.kt
  src/main/kotlin/com/psr/psr/review/dto/ReviewDetailTop.kt
Labels: 📒 docs

#193 [docs] 리뷰, 요청, 알림, 문의 스웨거 설명 설정
  src/main/kotlin/com/psr/psr/inquiry/controller/InquiryController.kt
  src/main/kotlin/com/psr/psr/inquiry/dto/InquiryAnswerReq.kt
  src/main/kotlin/com/psr/psr/inquiry/dto/InquiryRes.kt
  src/main/kotlin/com/psr/psr/notification/controller/NotificationController.kt
  src/main/kotlin/com/psr/psr/notification/dto/NotiList.kt
  src/main/kotlin/com/psr/psr/notification/dto/NotificationListRes.kt
  src/main/kotlin/com/psr/psr/order/controller/OrderController.kt
  src/main/kotlin/com/psr/psr/order/dto/OrderListRes.kt
  src/main/kotlin/com/psr/psr/order/dto/OrderReq.kt
  src/main/kotlin/com/psr/psr/order/dto/OrderRes.kt
  src/main/kotlin/com/psr/psr/review/controller/ReviewController.kt
  src/main/kotlin/com/psr/psr/review/dto/ReviewListRes.kt
  src/main/kotlin/com/psr/psr/review/dto/ReviewReq.kt
Labels: ☀️ seoyeon, 📒 docs

#195 [feat] 채팅방 등록 API
  src/main/kotlin/com/psr/psr/chat/controller/ChatRoomController.kt
  src/main/kotlin/com/psr/psr/chat/entity/ChatMessage.kt
  src/main/kotlin/com/psr/psr/chat/entity/ChatRoom.kt
  src/main/kotlin/com/psr/psr/chat/service/ChatRoomService.kt
Labels: 🔮 feat, 😽 sojung

#198 [feat] 채팅방 나가기 API
  src/main/kotlin/com/psr/psr/chat/controller/ChatRoomController.kt
  src/main/kotlin/com/psr/psr/chat/entity/ChatRoom.kt
  src/main/kotlin/com/psr/psr/chat/repository/ChatRoomRepository.kt
  src/main/kotlin/com/psr/psr/chat/service/ChatRoomService.kt
  src/main/kotlin/com/psr/psr/global/exception/BaseResponseCode.kt
Labels: 🔮 feat, 😽 sojung

#202 [feat] 채팅 상세 조회 API
  src/main/kotlin/com/psr/psr/chat/controller/ChatController.kt
  src/main/kotlin/com/psr/psr/chat/dto/response/ChatMessageRes.kt
  src/main/kotlin/com/psr/psr/chat/dto/response/ChatMessagesRes.kt
  src/main/kotlin/com/psr/psr/chat/dto/response/GetChatMessagesRes.kt
  src/main/kotlin/com/psr/psr/chat/repository/ChatMessageCustom.kt
  src/main/kotlin/com/psr/psr/chat/repository/ChatMessageRepositoryImpl.kt
  src/main/kotlin/com/psr/psr/chat/service/ChatService.kt
Labels: 🔮 feat, 😽 sojung
